apiVersion: v1
kind: Namespace
metadata:
  name:  ns-customer
  labels:
    name: ns-customer

---
apiVersion: v1
kind: Secret
metadata:
  name: customer-mongo-secrets
  namespace: ns-customer 
type: Opaque
data:
  customer-mongo-root-username: Y2xvdWQtd2FycmlvcnM=
  customer-mongo-root-password: Y2xvdWQtd2FycmlvcnM=
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  customer-mongo
  namespace: ns-customer 
  labels:
    name:  customer-mongo 
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: customer-mongo 
  template:
    metadata:
      labels:
        name:  customer-mongo
    spec:
      containers:
      - image:  mongo 
        name:  customer-mongo
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "250m"
            memory: "250Mi"
          limits:
            cpu: "1500m"
            memory: "2500M"    
        ports:
        - containerPort:  27017
          name:  customer-mongo

---
kind: Service
apiVersion: v1
metadata:
  name:  customer-mongo-service
  namespace: ns-customer
spec:
  selector:
    name: customer-mongo
  ports:
  - name:  customer-mongo
    protocol: TCP
    port:  27017
    targetPort:  27017
