apiVersion: v1
kind: Namespace
metadata:
  name:  ns-cloud-wariors
  namespace: ns-cloud-wariors
  labels:
    name: ns-cloud-wariors

---
apiVersion: v1
kind: Secret
metadata:
  name: customer-secrets
  namespace: ns-cloud-wariors
type: Opaque
data:
  customer-app-secret: Y2xvdWQtd2FycmlvcnM=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-configmap
  namespace: ns-cloud-wariors
data:
  mongo_url: mongodb://customer-mongo-service/customer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  namespace: ns-cloud-wariors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: caesarsage/customer:v3
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: customer-configmap
              key: mongo_url
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: customer-secrets
              key: customer-app-secret
        resources:
          requests:
              cpu: 250m
              memory: 350Mi
          limits:
            memory: "700Mi"
            cpu: "1100m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
        ports:
        - containerPort: 8001


---
kind: Service
apiVersion: v1
metadata:
  name:  customer-service
  namespace: ns-cloud-wariors
spec:
  selector:
    app:  customer
  # type:  LoadBalancer
  ports:
  - name:  customer
    port:  8001
    targetPort:  8001
    # nodePort: 30000
    protocol:  TCP
